service: notification-service
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - ${file(serverless/iam/SendMailIAM.yml):SendMailIAM}
    - ${file(serverless/iam/MailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    MailQueue:
      ${file(serverless/resources/MailQueue.yml):MailQueue}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: 
      Fn::GetAtt:
        - MailQueue
        - Arn
  bundle:
    linting: false