service: sls-auction-app
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  hello:
    handler: src/handlers/createAuction.handler
    events: 
      - http:
          path: /auction
          method: POST

custom:
  bundle:
    linting: false
  
