service: sls-auction-app
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
  iamRoleStatements:
    - ${file(serverless/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(serverless/iam/MailQueueIAM.yml):MailQueueIAM}
    - ${file(serverless/iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
resources:
  Resources:
    AuctionsTable:
      ${file(serverless/resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket:
      ${file(serverless/resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy:
      ${file(serverless/resources/AuctionsBucket.yml):AuctionsBucketPolicy} 
     
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events: 
      - http:
          path: /auctions
          method: POST
          cors: true
          authorizer: ${self:custom.authorizer}

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events: 
      - http:
          path: /auctions
          method: GET
          cors: true
          authorizer: ${self:custom.authorizer}

  getAuction:
    handler: src/handlers/getAuction.handler
    events: 
      - http:
          path: /auctions/{id}
          method: GET
          cors: true
          authorizer: ${self:custom.authorizer}

  placeBid:
    handler: src/handlers/placeBid.handler
    events: 
      - http:
          path: /auctions/{id}
          method: PATCH
          cors: true
          authorizer: ${self:custom.authorizer}

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events: 
      - http:
          path: /auctions/{id}/picture
          method: POST
          cors: true
          authorizer: ${self:custom.authorizer}

  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events: 
    #   - schedule: rate(1 minute)

custom:
  authorizer: arn:aws:lambda:${self:provider.region}:338975015168:function:auth-service-${self:provider.stage}-auth
  AuctionsTable:
    name: !Ref AuctionsTable
    arn:  !GetAtt AuctionsTable.Arn
  MailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
  AuctionsBucket:
    name: auctions-bucket-qwerty1485-${self:provider.stage}
    # arn: ${cf:${self:service}-${self:provider.stage}-auctions-bucket.Arn}
    region: ${self:provider.region}
  bundle:
    linting: false
  
