service: sls-auction-app
frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(serverless/iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable:
      ${file(serverless/resources/AuctionsTable.yml):AuctionsTable}
     
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events: 
      - http:
          path: /auctions
          method: POST

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events: 
      - http:
          path: /auctions
          method: GET

  getAuction:
    handler: src/handlers/getAuction.handler
    events: 
      - http:
          path: /auctions/{id}
          method: GET

  placeBid:
    handler: src/handlers/placeBid.handler
    events: 
      - http:
          path: /auctions/{id}
          method: PATCH

  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events: 
    #   - schedule: rate(1 minute)

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn:  !GetAtt AuctionsTable.Arn
  bundle:
    linting: false
  
