AuctionsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AuctionsBucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 1

AuctionsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: 
      Ref: AuctionsBucket
    PolicyDocument:
      Statement:
        - Effect: "Allow"
          Principal:
            AWS:
              - Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
          Action: 
            - "s3:GetObject"
          Resource: arn:aws:s3:::${self:custom.AuctionsBucket.name}/*